services:
  mysql-service:
    image: mysql:8.0  # Use the official MySQL image
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ahli  # Root password
      MYSQL_DATABASE: plcinstdb         # Default database to create
      MYSQL_USER: root                 # Custodockm user
      MYSQL_PASSWORD: ahli         # Custom user password
    ports:
      - "3306:3306"  # Map port 3306 on the host to port 3306 on the container
    volumes:
      - /db/mydb:/var/lib/mysql  # Persist MySQL data to a volume
#     networks:
#       - mysql_network

# networks:
#   mysql_network:  # Define a network for the MySQL service