# # three node (two workers) cluster config
# kind: Cluster
# apiVersion: kind.x-k8s.io/v1alpha4
# nodes:
# - role: control-plane

# you can access by virtual machine ip address:30000
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /home/moh/plcInstProjct/instplcapp
        containerPath: /home/plcinstapp
    extraPortMappings:
    - containerPort: 30000
      hostPort: 30000
      protocol: TCP


