apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextjs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/plcinstapp
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextjs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi      
---
apiVersion: v1
kind: Pod
metadata:
  name: nextjs-app
  labels:
    app: nextjs-app
spec:
  containers:
    - name: nextjs-container
      image: node:latest

      # command: ["npm run dev"]
      command: ["/bin/bash", "-c", "ls -al /app && tail -f /dev/null"]  # Execute command and keep running

      # command: ["/bin/sh", "-c", "sleep 6000"]  # Add sleep before running the app
      workingDir: /app
      ports:
        - containerPort: 3000  # Next.js default port
      volumeMounts:
        - name: nextjs-code
          mountPath: /app  # Mount the volume to /app
  volumes:
    - name: nextjs-code
      hostPath:
        path: /home/plcinstapp/ # Path to your local Next.js application
        type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  type: NodePort
  selector:
    app: nextjs-app  # Matches the Pod's label
  ports:
    - protocol: TCP
      port: 80  # Service port
      targetPort: 3000  # Container port
      nodePort: 30000  # Expose on port 30000 on all nodes
